version: "3"

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=rocket-ts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=rocket-ts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
  pg_admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "juliomiguelsouzacosta@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "rootroot!"
    ports: 
      - "16543:80"
    depends_on:
      - db
    

  